### PR TITLE
Make clear random like "normal" clear weather

### PR DESCRIPTION
**Pull request by Kroppeb**

### CODE REVIEW

**Review by Kroppeb — COMMENTED** [review]
[wiki](https://minecraft.fandom.com/wiki/Commands/weather):
> If 0, resets to random weather duration

I can see the code where this happens for rain and thunder, clear is a bit more special, and I can't find it without genning sources or earth updating the class file indexer, but it seems to work

**Comment by Gaming32** [comment]
Huh, I tried to copy the code from `/weather clear`, but I must have messed something up.

**Comment by Kroppeb** [comment]
> Huh, I tried to copy the code from `/weather clear`, but I must have messed something up.

No, you didn't, if you don't specify a duration, it will use 5 minutes, but if you specify a duration of 0, it's random. It's incredibly weird.

**Comment by Gaming32** [comment]
Oh huh, that's very strange.

**Pull request merged**
